# This is a basic workflow that is manually triggered

name: Build with default profile - "slim-test"


on:
  release:
    types: [published, created, edited]
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_armor:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        slim_profile: ['slim', 'r1cl']

    steps:
    - name: Start job for profiles
      run: echo "Profile  ${{ matrix.slim_profile }}"

    - uses: actions/checkout@v2
      with:
        repository: 'ryohuang/slim-wrt'
        path: 'slim-wrt'
        
    - name: Install build tools
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
      run: |
        sudo apt-get update &&\
        sudo apt-get install -qqy --no-install-recommends build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo npm python-is-python3 ssh-client wget curl file screen && \
        sudo apt-get clean && \
        sudo rm -rf /var/lib/apt/lists/*

    - name: Showtime 
      run: |
        cd $GITHUB_WORKSPACE/slim-wrt
        echo "build with profile ${{ matrix.slim_profile }}"
        make SLIM_CFG_PROFILE=${{ matrix.slim_profile }} showtime
        
    - name: Show outputs and zip ipks
      run: |
        df -h
        echo "SHOW IMAGES"
        ls $GITHUB_WORKSPACE/slim-wrt/images/${{ matrix.slim_profile }}
        echo "SHOW PACKAGES"
        ls $GITHUB_WORKSPACE/slim-wrt/ipks/${{ matrix.slim_profile }}
        cd $GITHUB_WORKSPACE/slim-wrt/ipks
        zip -r ${{ matrix.slim_profile }}.zip ./${{ matrix.slim_profile }}
    
    - name: Rename build info files
      run: |
        set -x
        profile=${{ matrix.slim_profile }}
        cd $GITHUB_WORKSPACE/slim-wrt/images/$profile
        for filename in ./**; do
          name=${filename##*/}
          if echo "$name" | grep -qE "buildinfo|sha256sums"; then
            mv $name $profile-$name
          fi
        done

    - name: Show outputs after rename 
      run: |
        df -h
        echo "SHOW IMAGES"
        ls $GITHUB_WORKSPACE/slim-wrt/images/${{ matrix.slim_profile }}
        echo "SHOW PACKAGES"
        ls $GITHUB_WORKSPACE/slim-wrt/ipks

    - uses: actions/upload-artifact@v2
      with:
          name: ${{ matrix.slim_profile }}-images
          path: ${{ github.workspace }}/slim-wrt/images/${{ matrix.slim_profile }}/*

    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "./slim-wrt/images/${{ matrix.slim_profile }}/**;./slim-wrt/ipks/${{ matrix.slim_profile }}.zip"
        tags: true
        draft: true
        overwrite: true
